spring:
  security:
    oauth2:
      client:
        registration:
          spotify:
            client-id: 59631f2853fb41128ffcabfff10e9d03
            client-secret: f4bf7793f11343989b791fa3e04fd8bc
            authorization-grant-type: authorization_code
            redirect-uri: "https://music-app-oab8.onrender.com/login/oauth2/code/spotify"
            scope: user-read-email, user-read-private, user-library-read, user-library-modify, playlist-read-private, playlist-modify-private, playlist-modify-public, streaming, app-remote-control, user-read-playback-state, user-modify-playback-state
        provider:
          spotify:
            authorization-uri: https://accounts.spotify.com/authorize
            token-uri: https://accounts.spotify.com/api/token
            user-info-uri: https://api.spotify.com/v1/me
            user-name-attribute: id

server:
  port: 8080